version: '3'
services:
  db:
    image: postgres:11.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/bittomo
      - /bittomo/vendor
      - /bittomo/log
      - /bittomo/.git
      - bundle:/usr/local/bundle:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle:
    driver: local
